### ISSUE TITLE
Mac Mini M1 16G  无法使用

### ISSUE THREAD

**Issue by marcuslannister** [waylybaye/Swapman#4]
系统版本是 11.2.1

![image](https://user-images.githubusercontent.com/70784566/109304215-e5189680-7876-11eb-9d96-4d3e206de69a.png)

**Comment by waylybaye** [comment]
duplicated with #1

**Comment by Kyle-Ye** [comment]
> 系统版本是 11.2.1
> 
> ![image](https://user-images.githubusercontent.com/70784566/109304215-e5189680-7876-11eb-9d96-4d3e206de69a.png)

正常现象，请确认活动监视器中内存“已使用的交换”是否为非0
若为0，请打开了n个 app / n个Chrome窗口直到内存不足并使用swap后导致“已使用的交换”为非0
点击右上角的⏺️即可观察到使用swap的app
